### ISSUE TITLE
Cannot sign up

### ISSUE THREAD

**Issue by iHiD** [doctorsonrails/o_portfolio_api_old#2]
I get this response:
`{"detail": "You do not have permission to perform this action."}`

Could you see what's going on please? 
- Is this my fault or a bug? 
- Should I be using some sort of auth to do this, or just a normal post?

Thanks!

**Comment by MadMouse** [comment]
I am also getting this error.

**Comment by edwallitt** [comment]
Ditto here...

**Comment by edwallitt** [comment]
does it work with curl? (_asks rhetorically_)

**Comment by iHiD** [comment]
I've also established that it doesn't work if you pass auth params.
